### ISSUE TITLE
TypeError: connection.query(...).on is not a function

### ISSUE THREAD

**Issue by nyaazi** [projectSHAI/GOATstack#6]
When I try to start an app using Postgresql on Windows 10 I get the following error:
Do you have any idea what might be causing this?

TypeError: connection.query(...).on is not a function
    at Promise (C:\Users\PC\order\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:159:12)
    at Promise._execute (C:\Users\PC\order\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (C:\Users\PC\order\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Users\PC\order\node_modules\bluebird\js\release\promise.js:79:10)
    at Promise.tap.connection (C:\Users\PC\order\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:156:14)
    at PassThroughHandlerContext.finallyHandler (C:\Users\PC\order\node_modules\bluebird\js\release\finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (C:\Users\PC\order\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\PC\order\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\PC\order\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\PC\order\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\PC\order\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\PC\order\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\PC\order\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\PC\order\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

**Comment by projectSHAI** [comment]
I would make sure your PATH variable is corretly set for the `psql` command to be global.

Another thing I could think of is check the file `config/env/development.ts` make sure the `sql` property in the `devEnv` json object has the correct database username and password.
